name: CI
on:
  pull_request:
    branches: [ "production", "develop" ]

jobs:
  build:
    env:
      DATABASE_HOST: localhost
      DATABASE_PORT: 27017
      DATABASE_USER: mongo
      DATABASE_PASSWORD: mongodbpwd
    runs-on: ubuntu-latest
     # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      mongo:
        # Docker Hub image
        image: mongo:latest
        # Provide the password for mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: mongo
          MONGO_INITDB_ROOT_PASSWORD: mongodbpwd
          
        # Set health checks to wait until mongo has started
        options: >-
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 27017 on service container to the host
          - ${{env.DATABASE_PORT}}:${{env.DATABASE_PORT}}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Analyze with Sonar
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      run: mvn verify sonar:sonar -D sonar.host.url="https://sonarcloud.io" -D sonar.organization=${{secrets.SONAR_ORGANIZATION}} -D sonar.projectKey=${{secrets.SONAR_PROJECT}}
          
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
