name: CI
on:
  push:
    branches: [ "production","develop" ]
  pull_request:
    branches: [ "production", "develop" ]

jobs:
  build:
    env:
      DATABASE_URL: localhost:5432/
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    runs-on: ubuntu-latest
     # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Analyze with Sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn clean verify sonar:sonar \
        -Dsonar.token=$SONAR_TOKEN \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.organization=${{secrets.SONAR_ORGANIZATION}} \
        -Dsonar.projectKey=${{secrets.SONAR_PROJECT}}
          
    - name: Add coverage to PR
      id: jacoco
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: |
          ${{ github.workspace }}/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
